---
title: "Análisis de diversidad biológica"
subtitle: "Capacitación interna | Tecoatl Asesoría Ambiental y Soluciones Alternativas"
author: "Biol. Michell Romero"
format: revealjs
logo: logo_TCT_negro.png   #agregando el logo
slide-number: c/t          #número de diapositiva
transition: fade           #transición transparente
css: styles.css
---

## ¿Qué vamos a aprender hoy?

::: incremental
-   Recordar el concepto general de diversidad en un contexto ecológico
-   Conocer los distintos estimadores de riqueza
-   Recordar los índices de diversidad tradicionales
-   Conocer el análisis de diversidad mediante Números de Hill
-   Conocer la forma más actual de estimar la diversidad con iNext en R y RStudio
:::

## Primero definamos diversidad

La definición más amplia y aceptada en ecología (modificado de Magurran, 2004):

*la diversidad es una propiedad emergente de un nivel determinado de organización biológica, medida o estimada en una escala dada, y estará definida por la conjugación de tres elementos: **riqueza, abundancia y composición*** *de elementos diferentes.*

Es importante recordar el tipo de diversidad que se pretende medir: diversidad genética, de especies, comunidades, etc.

## Diversidad a distintas escalas

Whittacker (1960) describe tres términios para medir la diversidad a distintas escalas espaciales: diversidad alfa, beta y gamma. 

::: incremental
- Diversidad alfa:Riqueza de especies de una muestra o comunidad.
- Diversidad beta:Cambio de composición de especies entre una comunidad y otra o el grado de diferenciación de comunidades.
- Diversidad gamma:Diversidad general de un conjunto de comunidades a mayor escala (geográfica)
:::

## Ejemplo de una comunidad

```{r echo=FALSE}
library(DT)

# Crear matriz de presencia/ausencia
Comunidades <- data.frame(
  Especie   = c("A", "B", "C", "D", "E", "F", "G"),
  Bosque    = c(1,   1,   1,   1,   1,   0,   0),
  Matorral  = c(1,   0,   1,   1,   0,   1,   0),
  Selva     =c(1,   1,   0,   0,   0,   0,   1)
)

datatable(Comunidades, 
          options = list(pageLength = 4),
          caption = "Tabla dinámica de presencia/ausencia de especies en comunidades")
                       
```
